// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>


using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CoolCode.Linq;
using FKS.Component.Tools;
using FKS.Site.Models;
using FKS.Site.Helper.Attributes;
using FKS.Site.Web.Controllers.BaseControllers;
using FKS.Core.Models.Hardware;
using FKS.Site.Helper.Logging;

namespace FKS.Site.Web.Controllers.Controllers
{
    partial class EquipmentViewController
    {
        partial void SetQueryBuilder(Pagination pagination)
        {
            IQueryBuilder<Equipment> queryBuilder = QueryBuilder.Create<Equipment>();

            if (pagination.KeyValues != null)
            {
                foreach (KeyValue kv in pagination.KeyValues)
                {
                    if (kv.Key.Equals("PropertyInfo"))
                    {
                        queryBuilder.Equals(s => s.PropertyInfo, int.Parse(kv.Value));
                    }
                    else if (kv.Key.Equals("PositionInfo"))
                    {
                        queryBuilder.Equals(s => s.PositionInfo, int.Parse(kv.Value));
                    }
                    else if (kv.Key.Equals("Status"))
                    {
                        queryBuilder.Equals(s => s.Status, int.Parse(kv.Value));
                    }
                }
            }

            if (!User.IsInRole("管理员"))
            {
                queryBuilder.Equals(s => s.UserName, User.Identity.Name);
            }

            this.ViewQueryBuilder = queryBuilder;
        }

        partial void DoCheckExist(Equipment model, OperationResult res)
        {
            var equip = this.SiteContract.Equipments.SingleOrDefault(m => m.CollectionCode.Equals(model.CollectionCode));

            if (equip != null && !string.IsNullOrEmpty(equip.CollectionCode))
            {
                res.ResultType = OperationResultType.Error;
                res.Message = string.Format(@"操作失败，已存在设备ID为：{0}的用户！", equip.CollectionCode);
            }

            this.IsExist = false;
        }

    }
}



