// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
//	   如存在本生成代码外的新需求，请在相同命名空间下创建同名分部类进行实现。
// </auto-generated>


using System;
using System.ComponentModel.Composition;
using System.Linq;

using FKS.Component.Data;
using FKS.Core.Models.Account;


namespace FKS.Core.Data.Repositories.Account.Impl
{
	/// <summary>
    ///   仓储操作层实现——操作员扩展类
    /// </summary>
    [Export(typeof(IMemberExtendRepository))]
    public partial class MemberExtendRepository : EFRepositoryBase<MemberExtend, Int64>, IMemberExtendRepository
    { }
}
